export const routes = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password-confirm',
  PROJECTS: '/projects',
  LEARN: '/blogs',
  JOBS: '/jobs',
  FAQS: '/faqs',
  PRIVACY_POLICY: '/privacy-policy',
  FILM: '/film',
  FILM_UPDATE: '/film-update',
  APP: '/app',
  DASHBOARD: '/app/dashboard',
  USER_MANAGEMENT: '/app/profile/users',
  CURRENT_USERS: '/app/profile/users/current-users',
  USER_GROUPS: '/app/profile/users/groups',
};
